### ISSUE TITLE
GUI players not found

### ISSUE THREAD

**Issue by HuaDeity** [vitorgalvao/short-films-workflow#1]
### Workflow version

2024.2

### Alfred version

5.5 [2257]

### macOS version

Sonoma 14.4

### Debugger output

```alfred_debugger
[13:45:15.763] STDERR: Short Films[Run Script] Unable to find application named 'com.colliderli.iina'
```

### More details

The same issue with [Play Address #1](https://github.com/vitorgalvao/play-address-workflow/issues/1).

**Comment by vitorgalvao** [comment]
Thank you. Fixed and new version has been released.
